Q.1 Creating NumPy arrays

In [1]:
#a) Check the versiono of numpy and create 1D AND 2D arrays
import numpy as np
print("the version of numpy is", np.__version__)
a=np.array([1,2,3,4,5])
print("1D array:",a)
b=np.array([[1,2,3],[4,5,6]])
print("2D array:\n",b)

the version of numpy is 1.23.5
1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


In [2]:
#b) Check the data type and the dimension of created arrays
print("Data type of array a is: ",a.dtype)
print("Data type of array b is: ",b.dtype)
print("Dimension of array a: ",a.ndim)
print("Dimension of array b: ",b.ndim)

Data type of array a is:  int32
Data type of array b is:  int32
Dimension of array a:  1
Dimension of array b:  2


In [3]:
#c Find the size of each element in array
print("Size of each element in array: ", a.itemsize)
print("Size of each element in array: ", b.itemsize)


Size of each element in array:  4
Size of each element in array:  4


In [4]:
#d Find the number of rows and colums of 2D array
print("Number of rows and columns of 2D array are: ", b.shape)

Number of rows and columns of 2D array are:  (2, 3)


In [5]:
#e An array of shape (2,3) given, reshape the array into (3,2)
original_array = np.array(b)
reshaped_array = original_array.reshape((3, 2))
print("Original Array:\n", original_array)
print("\nReshaped Array:\n",reshaped_array)

Original Array:
 [[1 2 3]
 [4 5 6]]

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


Q.2 slicing of Arrays

In [6]:
#A 1D array [4,5,6,3,9,7], slice the array to get [6,3,9]
a = np.array([4,5,6,3,9,7])
print(a[2:5])

[6 3 9]


In [7]:
#B A 2D array is given as [[1,2,3],[4,5,6]]. Slice the array to get [[1,2]]
b = np.array([[1,2,3],[4,5,6]])
print(b[0:1,0:2])

[[1 2]]


Q.3 Join and splitting of NumPy arrays

In [8]:
#a concatenate two 1D arrays [4,5,6,7] and [3,4,1]
a=np.array([4,5,6,7])
b=np.array([3,4,1])
c=np.concatenate((a,b))
print(c)

[4 5 6 7 3 4 1]


In [9]:
#b Perform conacatenation of two 2D arrays in row by row manner
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print("Array a:\n",a)
print("Array b:\n",b)
print("Concatenation of two arrays in row by row manner:\n",np.concatenate((a,b)))


Array a:
 [[1 2 3]
 [4 5 6]]
Array b:
 [[ 7  8  9]
 [10 11 12]]
Concatenation of two arrays in row by row manner:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
#c split the array [4,5,6,3,9]  into 3 sub-arrays
x=np.array([4,5,6,3,9])
print(np.split(x,[1,3]))



[array([4]), array([5, 6]), array([3, 9])]


In [11]:
#d  Split the array[[1,2,3],[4,5,6],[7,8,9]] into three subarrays.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.split(a,3))



[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


Q.4 Searching elements in an array 

In [12]:
#a Given an array [1,2,3,4,5,4,4] Find the index of element 
arr=np.array([1,2,3,4,5,4,4])
print(np.where(arr==4))

(array([3, 5, 6], dtype=int64),)


In [13]:
#b Given a 2d array [[1,2,3],[4,5,6],[7,8,9],[10,11,12]] find the index of element 5


In [14]:
#c Given an array [1,2,3,4,5,6,7,8] find out the indices of odd elements and even elements


Q.5 SORTING OF ARRAYS

In [23]:
#a Sort the elements of given 1D array [6,5,1,2,9,10,36,7] in ascending and descending order
import numpy as np
array = np.array([6, 5, 1, 2, 9, 10, 36, 7])
ascending_sorted = np.sort(array)
descending_sorted = np.sort(array)[::-1]
print("Ascending sorted array:", ascending_sorted)
print("Descending sorted array:", descending_sorted)

Ascending sorted array: [ 1  2  5  6  7  9 10 36]
Descending sorted array: [36 10  9  7  6  5  2  1]


In [16]:
#b sort the elements of given 2D array [[5,3,7],[8,10,6],[40,-2,7]] in ascending and descending order
import numpy as np
array = np.array([[5, 3, 7], [8, 10, 6], [40, -2, 7]])
asc = np.sort(array, axis=None)
desc = np.sort(array, axis=None)[::-1]
asc = asc.reshape(array.shape)
desc = desc.reshape(array.shape)
print("Ascending order: \n", asc)
print("Descending order: \n", desc)

Q.6 Random no generation in NUMPY Arrays

In [17]:
#a Generate a 1-D array containing random integers from 0 to 20
import numpy as np
a = np.random.randint(0, 20, 10)
print(a)

In [1]:
#b Generate a 1D array containing 5 random floats
import numpy as np
a = np.random.rand(5)
print(a)

[0.18846148 0.21681085 0.69626761 0.20640051 0.51605827]


In [19]:
#c Generate a 2D array with 3 rows, each row containing 5 random integers from 0 to 50
import numpy as np
array = np.random.randint(0, 50, size=(3, 5))
print(array)

In [20]:
#d Generate a 2D array with 3 rows, each row containing 5 random numbers
import numpy as np
array = np.random.rand(3, 5, size=(3, 5))
print(array)

In [21]:
#e Given 1D array [6,5,1,2,9,10,36,7]. shuffle the elements of the array randomly
import numpy as np
arr = np.array([6, 5, 1, 2, 9, 10, 36, 7])
np.random.shuffle(arr)
print(arr)

In [2]:
#f given 2D array [[1,2,3][4,5,6][7,8,9][10,11,12]] shuffle the elements of given array randomly
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Original array:")
print(arr)
print("After shuffling:")
np.random.shuffle(arr)
print(arr)

Original array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
After shuffling:
[[ 4  5  6]
 [ 1  2  3]
 [10 11 12]
 [ 7  8  9]]
